/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.acompany.calculator;

import java.text.DecimalFormat;
import java.lang.Math;


/**
 *
 * @author CTRL
 */
public class CalculatorJFrame extends javax.swing.JFrame {
   
    double num1, num2, result;
    String operator;
    
    
    public CalculatorJFrame() {
        initComponents();
    }
    
    boolean operatorJustPressed = false;
    private void button(String number) {
        // Clear after AC, =, or %
        if (jTextField_Display2.getText().equals("AC") ||
            jTextField_Display3.getText().equals("=") ||
            jTextField_Display4.getText().equals("%")) {

            jTextField_Display2.setText("");
            jTextField_Display3.setText("");
            jTextField_Display4.setText("");
        }

        // If operator was just pressed, now we start inputting num2
        if (operatorJustPressed) {
            operatorJustPressed = false; // reset flag
            jTextField_Display.setText(jTextField_Display.getText() + number); // allow num2 to continue right after operator
        } else {
            jTextField_Display.setText(jTextField_Display.getText() + number); // normal case
        }
    }
    
    private String format(double result){
        if (result == (int) result){
            return String.valueOf((int) result);
        }
        else{
            DecimalFormat df = new DecimalFormat("#.##");
            return df.format(result); 
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField_Display4 = new javax.swing.JTextField();
        jTextField_Display3 = new javax.swing.JTextField();
        jTextField_Display2 = new javax.swing.JTextField();
        jTextField_Display = new javax.swing.JTextField();
        jButton_percentage = new javax.swing.JButton();
        jButton_Division = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_Multi = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_minus = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_equal = new javax.swing.JButton();
        jButton_decimal = new javax.swing.JButton();
        jButton_plus = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_root = new javax.swing.JButton();
        jButton_power = new javax.swing.JButton();
        jButton_fact = new javax.swing.JButton();
        jButton_tan = new javax.swing.JButton();
        jButton_cos = new javax.swing.JButton();
        jButton_sin = new javax.swing.JButton();
        jButton_pi = new javax.swing.JButton();
        jButton_round = new javax.swing.JButton();
        jButton_abs = new javax.swing.JButton();
        jButton_e = new javax.swing.JButton();
        jButton_1byx = new javax.swing.JButton();
        jButton_ln = new javax.swing.JButton();
        jButton_lg = new javax.swing.JButton();
        jToggleButton_2nd = new javax.swing.JToggleButton();
        jToggleButton_red = new javax.swing.JToggleButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(253, 253, 253));
        setMinimumSize(new java.awt.Dimension(415, 735));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_Display4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Display4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Display4.setBorder(null);
        jTextField_Display4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Display4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Display4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, 270, 25));

        jTextField_Display3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_Display3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Display3.setBorder(null);
        jTextField_Display3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Display3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Display3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 30, 25));

        jTextField_Display2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Display2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Display2.setBorder(null);
        jTextField_Display2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Display2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Display2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 30, 25));

        jTextField_Display.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        jTextField_Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 130));

        jButton_percentage.setBackground(new java.awt.Color(224, 224, 224));
        jButton_percentage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_percentage.setForeground(new java.awt.Color(255, 133, 21));
        jButton_percentage.setText("%");
        jButton_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_percentageActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 61, 61));

        jButton_Division.setBackground(new java.awt.Color(224, 224, 224));
        jButton_Division.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton_Division.setForeground(new java.awt.Color(255, 152, 0));
        jButton_Division.setText("÷");
        jButton_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DivisionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Division, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 61, 61));

        jButton_8.setBackground(new java.awt.Color(224, 224, 224));
        jButton_8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_8.setText("8");
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 61, 61));

        jButton_9.setBackground(new java.awt.Color(224, 224, 224));
        jButton_9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_9.setText("9");
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 61, 61));

        jButton_7.setBackground(new java.awt.Color(224, 224, 224));
        jButton_7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_7.setText("7");
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 61, 61));

        jButton_Multi.setBackground(new java.awt.Color(224, 224, 224));
        jButton_Multi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Multi.setForeground(new java.awt.Color(255, 152, 0));
        jButton_Multi.setText("X");
        jButton_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MultiActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 61, 61));

        jButton_5.setBackground(new java.awt.Color(224, 224, 224));
        jButton_5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_5.setText("5");
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 61, 61));

        jButton_6.setBackground(new java.awt.Color(224, 224, 224));
        jButton_6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_6.setText("6");
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 61, 61));

        jButton_4.setBackground(new java.awt.Color(224, 224, 224));
        jButton_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_4.setText("4");
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 61, 61));

        jButton_minus.setBackground(new java.awt.Color(224, 224, 224));
        jButton_minus.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton_minus.setForeground(new java.awt.Color(255, 152, 0));
        jButton_minus.setText("−");
        jButton_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 61, 61));

        jButton_2.setBackground(new java.awt.Color(224, 224, 224));
        jButton_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_2.setText("2");
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 61, 61));

        jButton_3.setBackground(new java.awt.Color(224, 224, 224));
        jButton_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_3.setText("3");
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 61, 61));

        jButton_1.setBackground(new java.awt.Color(224, 224, 224));
        jButton_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_1.setText("1");
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 61, 61));

        jButton_0.setBackground(new java.awt.Color(224, 224, 224));
        jButton_0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_0.setText("0");
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 61, 61));

        jButton_equal.setBackground(new java.awt.Color(224, 224, 224));
        jButton_equal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_equal.setText("=");
        jButton_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_equalActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 61, 61));

        jButton_decimal.setBackground(new java.awt.Color(224, 224, 224));
        jButton_decimal.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_decimal.setText(".");
        jButton_decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_decimalActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 61, 61));

        jButton_plus.setBackground(new java.awt.Color(224, 224, 224));
        jButton_plus.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton_plus.setForeground(new java.awt.Color(255, 152, 0));
        jButton_plus.setText("+");
        jButton_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 60, 130));

        jButton_Clear.setBackground(new java.awt.Color(255, 133, 21));
        jButton_Clear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear.setText("AC");
        jButton_Clear.setBorder(null);
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Clear.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 61, 61));

        jButton_delete.setBackground(new java.awt.Color(224, 224, 224));
        jButton_delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_delete.setForeground(new java.awt.Color(255, 133, 21));
        jButton_delete.setText("DEL");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 61, 61));

        jButton_root.setBackground(new java.awt.Color(224, 224, 224));
        jButton_root.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jButton_root.setText("√");
        jButton_root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rootActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_root, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 61, 61));

        jButton_power.setBackground(new java.awt.Color(224, 224, 224));
        jButton_power.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_power.setText("xʸ");
        jButton_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_powerActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_power, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 61, 61));

        jButton_fact.setBackground(new java.awt.Color(224, 224, 224));
        jButton_fact.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_fact.setText("x!");
        jButton_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_factActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 61, 45));

        jButton_tan.setBackground(new java.awt.Color(224, 224, 224));
        jButton_tan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_tan.setText("tan");
        jButton_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tanActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 61, 45));

        jButton_cos.setBackground(new java.awt.Color(224, 224, 224));
        jButton_cos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_cos.setText("cos");
        jButton_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 61, 45));

        jButton_sin.setBackground(new java.awt.Color(224, 224, 224));
        jButton_sin.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_sin.setText("sin");
        jButton_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sinActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 61, 45));

        jButton_pi.setBackground(new java.awt.Color(224, 224, 224));
        jButton_pi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_pi.setText("π");
        jButton_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_piActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 61, 61));

        jButton_round.setBackground(new java.awt.Color(224, 224, 224));
        jButton_round.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_round.setText("Rnd");
        jButton_round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_roundActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 61, 45));

        jButton_abs.setBackground(new java.awt.Color(224, 224, 224));
        jButton_abs.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_abs.setText("| x |");
        jButton_abs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_absActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_abs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 61, 45));

        jButton_e.setBackground(new java.awt.Color(224, 224, 224));
        jButton_e.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jButton_e.setText("e");
        jButton_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 61, 61));

        jButton_1byx.setBackground(new java.awt.Color(224, 224, 224));
        jButton_1byx.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_1byx.setText("1/x");
        jButton_1byx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1byxActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_1byx, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 61, 61));

        jButton_ln.setBackground(new java.awt.Color(224, 224, 224));
        jButton_ln.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_ln.setText("ln");
        jButton_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lnActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 61, 45));

        jButton_lg.setBackground(new java.awt.Color(224, 224, 224));
        jButton_lg.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_lg.setText("lg");
        jButton_lg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lgActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 61, 45));

        jToggleButton_2nd.setBackground(new java.awt.Color(224, 224, 224));
        jToggleButton_2nd.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jToggleButton_2nd.setText("2nd");
        jToggleButton_2nd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_2ndActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton_2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 61, 45));

        jToggleButton_red.setBackground(new java.awt.Color(224, 224, 224));
        jToggleButton_red.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jToggleButton_red.setText("red");
        jToggleButton_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_redActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton_red, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 61, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_percentageActionPerformed
        double value=Double.parseDouble(jTextField_Display.getText());
        double result = value/100;
        jTextField_Display.setText(format(result));
        jTextField_Display3.setText("=");
        jTextField_Display4.setText("%");
    }//GEN-LAST:event_jButton_percentageActionPerformed

    private void jButton_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DivisionActionPerformed
        try {
            String currentText = jTextField_Display.getText();

            if (currentText.endsWith("+") || currentText.endsWith("-") || currentText.endsWith("×") || currentText.endsWith("÷")) {
                return; // avoid duplicate operator
            }

            operator = "/";
            operatorJustPressed = true;

            jTextField_Display.setText(currentText + "÷");
        } catch (Exception ex) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_DivisionActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        button("8");
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        button("9");
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        button("7");
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MultiActionPerformed
        try {
            String currentText = jTextField_Display.getText();

            if (currentText.endsWith("+") || currentText.endsWith("-") || currentText.endsWith("×") || currentText.endsWith("÷")) {
                return; // avoid duplicate operator
            }

            operator = "*";
            operatorJustPressed = true;

            jTextField_Display.setText(currentText + "×");
        } catch (Exception ex) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_MultiActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        button("5");
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        button("6");
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        button("4");
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusActionPerformed
        try {
            String currentText = jTextField_Display.getText();

            if (currentText.endsWith("+") || currentText.endsWith("-") || currentText.endsWith("×") || currentText.endsWith("÷")) {
                return; // avoid duplicate operator
            }

            operator = "-";
            operatorJustPressed = true;

            jTextField_Display.setText(currentText + "-");
        } catch (Exception ex) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_minusActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        button("2");
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        button("3");
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        button("1");
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jTextField_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DisplayActionPerformed

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        button("0");
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_equalActionPerformed
        jTextField_Display3.setText("=");
        jTextField_Display4.setText(jTextField_Display.getText());
        
        
        String expression = jTextField_Display.getText(); // e.g. "5+3"
        
        // Replace symbols with real operators
        expression = expression.replace("×", "*");
        expression = expression.replace("÷", "/");
        
        int opIndex = expression.indexOf(operator);       // find position of operator
        
        if (opIndex == -1) {
        jTextField_Display.setText("Invalid");
        return;
        }
        
        // Extract num1 from start to operator index
        num1 = Double.parseDouble(expression.substring(0, opIndex));

        // Extract num2 from after operator till end
        num2 = Double.parseDouble(expression.substring(opIndex + 1));

        result = 0;
        switch (operator) {
            case "+":
                result = num1 + num2;
                break;
            case "-":
                result = num1 - num2;
                break;
            case "*":
                result = num1 * num2;
                break;
            case "/":
                if (num2 == 0) {
                    jTextField_Display.setText("Error");
                    return;
                }
                result = num1 / num2;
                break;
            case "^":
                result = Math.pow(num1, num2);
                break;
            default:
                jTextField_Display.setText("Error");
                return;
        }

        jTextField_Display.setText(format(result));

    }//GEN-LAST:event_jButton_equalActionPerformed

    private void jButton_decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_decimalActionPerformed
        if (jTextField_Display.getText().isEmpty()) {
            jTextField_Display.setText("0.");
            }
        else{
            if (! jTextField_Display.getText().contains(".")) {
            jTextField_Display.setText(jTextField_Display.getText() + jButton_decimal.getText());
            }
        }
    }//GEN-LAST:event_jButton_decimalActionPerformed

    private void jButton_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plusActionPerformed
        try {
            String currentText = jTextField_Display.getText();

            if (currentText.endsWith("+") || currentText.endsWith("-") || currentText.endsWith("×") || currentText.endsWith("÷")) {
                return; // avoid duplicate operator
            }

            operator = "+";
            operatorJustPressed = true;

            jTextField_Display.setText(currentText + "+");
        } catch (Exception ex) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_plusActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        jTextField_Display.setText("");
        jTextField_Display3.setText("");
        jTextField_Display4.setText("");
        operator = "";
        jTextField_Display2.setText("AC");
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jTextField_Display2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Display2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Display2ActionPerformed

    private void jTextField_Display3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Display3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Display3ActionPerformed

    private void jTextField_Display4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Display4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Display4ActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        jTextField_Display2.setText("");
        jTextField_Display3.setText("");
        jTextField_Display4.setText("");

        String currentText = jTextField_Display.getText();

        if (currentText.length() > 0){
            String newText = currentText.substring(0, currentText.length()-1);
            jTextField_Display.setText(newText);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_powerActionPerformed
        try {
            String currentText = jTextField_Display.getText();

            // Prevent multiple operators like 5^^3
            if (currentText.endsWith("+") || currentText.endsWith("-") ||
                currentText.endsWith("×") || currentText.endsWith("÷") || currentText.endsWith("^")) {
                return;
            }

            operator = "^"; // Store real operator
            operatorJustPressed = true; // Let number button know we're ready for num2

            jTextField_Display.setText(currentText + "^"); // Show num1^ on display
        } catch (Exception ex) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_powerActionPerformed

    private long factorial(int n) {
        if (n < 0) return -1;
        long result = 1;
        for (int i = 1; i <= n; i++) {
            result *= i;
        }
        return result;
    }
    private void jButton_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_factActionPerformed
            try {
                String input = jTextField_Display.getText();
                int number = Integer.parseInt(input);

                if (number < 0) {
                    jTextField_Display.setText("Error");
                    return;
                }

                long fact = factorial(number);

                jTextField_Display.setText(String.valueOf(fact));
                jTextField_Display3.setText("=");
                jTextField_Display4.setText(number + "!");

            } catch (Exception e) {
                jTextField_Display.setText("Error");
            }
    }//GEN-LAST:event_jButton_factActionPerformed

    private void jButton_rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rootActionPerformed
        num1 = Double.parseDouble(jTextField_Display.getText());
        result = Math.sqrt(num1);
        jTextField_Display.setText(format(result));
        jTextField_Display3.setText("=");
        jTextField_Display4.setText("√" + (int) num1);
    }//GEN-LAST:event_jButton_rootActionPerformed

    private void jButton_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tanActionPerformed
        try {
            num1 = Double.parseDouble(jTextField_Display.getText());

            if (isSecondMode) {
                result = isRadian
                    ? Math.atan(num1)
                    : Math.toDegrees(Math.atan(num1));
            } else {
                result = isRadian
                    ? Math.tan(num1)
                    : Math.tan(Math.toRadians(num1));
            }

            jTextField_Display.setText(format(result));
            jTextField_Display3.setText("=");
            jTextField_Display4.setText(jButton_tan.getText() + "(" + (int) num1 + ")");

        } catch (Exception e) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_tanActionPerformed

    private void jButton_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_piActionPerformed
        jTextField_Display.setText(String.valueOf(Math.PI));
        jTextField_Display3.setText("=");
        jTextField_Display4.setText("π");
    }//GEN-LAST:event_jButton_piActionPerformed

    private void jButton_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sinActionPerformed
        try {
            num1 = Double.parseDouble(jTextField_Display.getText());

            if (isSecondMode) {
                result = isRadian
                    ? Math.asin(num1)
                    : Math.toDegrees(Math.asin(num1));
            } else {
                result = isRadian
                    ? Math.sin(num1)
                    : Math.sin(Math.toRadians(num1));
            }

            jTextField_Display.setText(format(result));
            jTextField_Display3.setText("=");
            jTextField_Display4.setText(jButton_sin.getText() + "(" + (int) num1 + ")");

        } catch (Exception e) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_sinActionPerformed

    private void jButton_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cosActionPerformed
        try {
            num1 = Double.parseDouble(jTextField_Display.getText());

            if (isSecondMode) {
                result = isRadian
                    ? Math.acos(num1)
                    : Math.toDegrees(Math.acos(num1));
            } else {
                result = isRadian
                    ? Math.cos(num1)
                    : Math.cos(Math.toRadians(num1));
            }

            jTextField_Display.setText(format(result));
            jTextField_Display3.setText("=");
            jTextField_Display4.setText(jButton_cos.getText() + "(" + (int) num1 + ")");

        } catch (Exception e) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_cosActionPerformed

    private void jButton_absActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_absActionPerformed
        num1 = Double.parseDouble(jTextField_Display.getText());
        result = Math.abs(num1);
        jTextField_Display.setText(format(result));
    }//GEN-LAST:event_jButton_absActionPerformed
    
    private boolean isSecondMode = false;
    
    private void jToggleButton_2ndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_2ndActionPerformed
        isSecondMode = !isSecondMode;

        if (isSecondMode) {
            jButton_sin.setText("sin⁻¹");
            jButton_cos.setText("cos⁻¹");
            jButton_tan.setText("tan⁻¹");
        } else {
            jButton_sin.setText("sin");
            jButton_cos.setText("cos");
            jButton_tan.setText("tan");
        }
    }//GEN-LAST:event_jToggleButton_2ndActionPerformed

    private void jButton_lgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lgActionPerformed
        num1 = Double.parseDouble(jTextField_Display.getText());
        result = Math.log10(num1);
        jTextField_Display.setText(format(result));
        jTextField_Display3.setText("=");
        jTextField_Display4.setText("log" + "(" + (int) num1 + ")");
    }//GEN-LAST:event_jButton_lgActionPerformed

    private void jButton_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lnActionPerformed
        num1 = Double.parseDouble(jTextField_Display.getText());
        result = Math.log(num1);
        jTextField_Display.setText(format(result));
        jTextField_Display3.setText("=");
        jTextField_Display4.setText("ln" + "(" + (int) num1 + ")");
    }//GEN-LAST:event_jButton_lnActionPerformed

    private void jButton_1byxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1byxActionPerformed
        num1 = Double.parseDouble(jTextField_Display.getText());
        if (num1 != 0) {
            result = 1 / num1;
            jTextField_Display.setText(format(result));
            jTextField_Display3.setText("=");
            jTextField_Display4.setText("1/" + (int) num1);
        } else {
            jTextField_Display.setText("ERROR");
        }
    }//GEN-LAST:event_jButton_1byxActionPerformed

    private void jButton_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eActionPerformed
        jTextField_Display.setText(String.valueOf(Math.E));
        jTextField_Display3.setText("=");
        jTextField_Display4.setText("e");
    }//GEN-LAST:event_jButton_eActionPerformed

    private void jButton_roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_roundActionPerformed
        try {
            double value = Double.parseDouble(jTextField_Display.getText());
            long rounded = Math.round(value);
            jTextField_Display.setText(String.valueOf(rounded));
        } catch (Exception e) {
            jTextField_Display.setText("Error");
        }
    }//GEN-LAST:event_jButton_roundActionPerformed
    
    private boolean isRadian = true;
    private void jToggleButton_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_redActionPerformed
        isRadian = !isRadian;
        jToggleButton_red.setText(isRadian ? "red" : "deg");

    }//GEN-LAST:event_jToggleButton_redActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_1byx;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Division;
    private javax.swing.JButton jButton_Multi;
    private javax.swing.JButton jButton_abs;
    private javax.swing.JButton jButton_cos;
    private javax.swing.JButton jButton_decimal;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_e;
    private javax.swing.JButton jButton_equal;
    private javax.swing.JButton jButton_fact;
    private javax.swing.JButton jButton_lg;
    private javax.swing.JButton jButton_ln;
    private javax.swing.JButton jButton_minus;
    private javax.swing.JButton jButton_percentage;
    private javax.swing.JButton jButton_pi;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_power;
    private javax.swing.JButton jButton_root;
    private javax.swing.JButton jButton_round;
    private javax.swing.JButton jButton_sin;
    private javax.swing.JButton jButton_tan;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_Display;
    private javax.swing.JTextField jTextField_Display2;
    private javax.swing.JTextField jTextField_Display3;
    private javax.swing.JTextField jTextField_Display4;
    private javax.swing.JToggleButton jToggleButton_2nd;
    private javax.swing.JToggleButton jToggleButton_red;
    // End of variables declaration//GEN-END:variables
}
